import type { NextPage } from 'next'
import Head from 'next/head'
import Card from '../components/general/Card'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a >FE Challenges</a>
        </h1>

        <p className={styles.description}>
          View my portafolio
          <a href='https://www.guilad.me' className={styles.link}>www.guilad.me</a>
        </p>
    
        <div className={styles.grid}>
          <Card title='Weather' description='Weather Api | Jest | TS | Radix' link='weather' />
          <Card title='Examples' description='Discover and deploy boilerplate example Next.js projects.' link='https://github.com/vercel/next.js/tree/canary/examples' />
          <Card title='Examples' description='Discover and deploy boilerplate example Next.js projects.' link='https://github.com/vercel/next.js/tree/canary/examples' />
          <Card title='Examples' description='Discover and deploy boilerplate example Next.js projects.' link='https://github.com/vercel/next.js/tree/canary/examples' />

        </div>
      </main>

      <footer className={styles.footer}>
        <p>
          All the challenges are taked from internet.
        </p>
        <p>if you are the owner of any of them and you want to remove it, please contact me.</p>
      </footer>
    </div >
  )
}

export default Home
